import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
# padding.x = 10
# padding. 
opacity = 1
blur = true

decorations = "none"

[font]
normal.family = "Hack Nerd Font"

#regular
size = 10

[[keyboard.bindings]]
action = "Paste"
key = "p"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "c"
mods = "Alt"


#for video
# size = 35.0
